using UnityEngine;
using UnityEngine.UI;
using TMPro;
using UnityEngine.SceneManagement;

public class PasarNivel2 : MonoBehaviour
{

    public Palanca palanca;
    public string nivel;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnTriggerEnter2D(Collider2D other)
    {
    if (other.CompareTag("Player") && palanca.puerta==true)
    {

        SceneManager.LoadScene(nivel);
    }
         
                 
    }
}
